version: 2
jobs:
  build:
    docker:
      - image: gradle:jdk8
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}
      - run: gradle check

# TODO react to master merges and automatically generate docs (push with `[skip ci]`)
# TODO react to tags and automatically publish
# TODO react to tags and create GitHub release
